### ISSUE TITLE
Distribution & collection option with cspy

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#14]
The following variant described in Salani and Righini's article should be fairly easy to implement, now that we are confident with time windows and its cutom REF :

![image](https://user-images.githubusercontent.com/19840033/80734112-f685fa80-8b0e-11ea-9fb8-75e3ca102c36.png)

For the backwards custom REF : 

![image](https://user-images.githubusercontent.com/19840033/80734224-26350280-8b0f-11ea-8254-12b09814688d.png)

**Comment by torressa** [comment]
Cool, I'll make a start on this probably tomorrow

**Comment by torressa** [comment]
I think this works, I'm a bit confused by the difference between pick-delivery vs distribution-collection.
Will read up on it.
Also, the ortools test I've added seems to be faster than the LP.

**Comment by Kuifje02** [comment]
Great, I will take a look !

> I'm a bit confused by the difference between pick-delivery vs distribution-collection.

Pickup and delivery : you have to pickup a good from a vertex A and bring it to a vertex B. Pairs (A,B) are given and called "requests" (B requests a good from A).

Distribution and collection : you have to service each node with a pickup and a delivery : when you reach a vertex A, you have to deliver its demand d(A) (which is loaded at the depot)+ pick up some waste matter p(A) and bring it back to the depot.

**Comment by torressa** [comment]
Sweet! Thanks
Just had a quick google about the pickup and delivery and found this [paper](https://backend.orbit.dtu.dk/ws/portalfiles/portal/4128533/PDPTW-BCP-TS-v3.pdf).
End of page 10 basically says that the bidirectional algorithm won't work due to dominance conditions for backward labels. 
Might still be worth running these with `direction="forward"` after we figure out how to model it

**Comment by Kuifje02** [comment]
great work @torressa !
