### ISSUE TITLE
Unit tests take forever

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#16]
Unit tests (which are essentially non regression tests) are quite long.

I do think it is a good approach to have them all while developing. But maybe once things are stable we should consider smaller data sets ? Note sure, just thinking and wondering what you think.

**Comment by torressa** [comment]
I agree!
It's pretty useful to have them as tests, so maybe we could split them into two folders `tests/unittests/` and `tests/benchmarks/`.
The CI can run the unit tests and we can run the rest occasionally.
In the future we can even have a scheduled weekly CI run with no timeouts that runs the benchmark tests.

**Comment by Kuifje02** [comment]
That is a great idea !
Three little things :
1. great work with the distribution and collection enhancement ! cspy is great !
2. I have added an example (with the ortools data set) in the form of a jupyter notebook (as you did with jpath, I thought that was really smart). I will develop the example to show the different options available. 
3. I am working on some tests with other data sets to analyze the performance of different heuristic strategies for the subproblem. I will send you the analysis when I get something nice.

**Comment by torressa** [comment]
1. Haha thanks man! It took a while to get it to work but it's easy to make those kind off changes now
2. Nicely done! I've seen it in loads of places and it's really cool that github renders notebooks
3. That is really useful because I have no idea! Look forward to it

Great work to you too man! Really putting in a lot of work!
Sorry I haven't been contributing that much, have a big deadline this month. Will be free after I'm done.
