### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#20]
I started working on the [docs](https://vrpy.readthedocs.io/en/dev/), trying to keep the same spirit and structure as cspy. Feel free to modify anything you want, in any way you want, or to simply make suggestions.

- [x] Complete the examples
- [x] Detail the VehicleRoutingProblem class
- [ ] Rename vrpy.main (?)

**Comment by torressa** [comment]
Nice man! Definitely will! Probs at some point this week.
By the way, I've found a dominance property that I think is going to bring a fair amount of speed up for the bidirectional algorithm. It's similar to the version that I had before we realised that it didn't work all the time. Basically discards all the extensions of paths that are proven to be dominated. In the elementary case, it's not so harsh (needs an extra check on nodes) but it still discards a fair few.
It requires a fair amount of work so instead I'll probs do both the parallelisation and this dominance thing at the same time.

**Comment by Kuifje02** [comment]
This is great! I'll do as much as I can with the docs and the examples in the mean time.

**Comment by torressa** [comment]
Just proof read the docs, looking pretty good! Really like the citation thing, might steal it.
Added a few spaces and re-indented some codeblocks but still have to see how it actually looks.
Tried to fill in the missing figures for the or-tools example, but not quite sure how to generate them with the new improved version! 
Btw, really good job cleaning all the duplicate stuff, turned out really neat.
Thanks for adding my name to the authors lists, but I don't think its fair given that you've done all the work! I'm more than happy to be in the dependency list haha
