### ISSUE TITLE
Dead code ?

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#6]
Did you write this bit of code for a particular reason ? I may be wrong but I don't think it is ever read (tests pass when it is commented).

https://github.com/Kuifje02/vrpy/blob/662ad3961891ba3556bbf71f8e3b608996de8a42/vrpy/subproblem_lp.py#L14-L18

**Comment by torressa** [comment]
Hey, it doesn't fail because they get redefined after you call formulate in
https://github.com/Kuifje02/vrpy/blob/662ad3961891ba3556bbf71f8e3b608996de8a42/vrpy/subproblem_lp.py#L53-L55

I think the attributes for the class should be called in the init method. However with the inheritance you need to explicitly pass the arguments you don't want to the parent class

**Comment by torressa** [comment]
Take a look. Sorry for the reformating again

**Comment by torressa** [comment]
Also, can't figure out why the tests are failing... :thinking:

**Comment by Kuifje02** [comment]
No problem for the formating. I use black. Which one do you use ? I can switch to yours I have no preference
