### ISSUE TITLE
modeling elementarity with resources

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#7]
Elementarity should be modelled as described below. 

So if I understood correctly this requires |V|+1 extra resources (?). One for each vertex, and one for tracking elementarity feasibility. Elementarity is expensive :) 

![image](https://user-images.githubusercontent.com/19840033/78682893-e2bfed80-78ee-11ea-940e-a33518e25c3f.png)

**Comment by torressa** [comment]
Wow, OK, that could be a lot of resources... Pretty good test for the custom REFs stuff I was just trying to fix

**Comment by torressa** [comment]
Turns out that the elementarity resources mess up dominance really badly and that the algorithm already ensures elementary paths. So this is not needed.
With this change and using the newest cspy version, both `direction="forward"` and `direction="backward"` give optimal results for the solomon case.

**Comment by Kuifje02** [comment]
O really ? that is curious ! 
Ok I will do some more tests today on Solomon's instances. 
I hope this doesn't mess up cspy ! Or at least that it contributes to make it more robust !

**Comment by torressa** [comment]
Cool! It doesn't, makes the last stage faster.
The dominance issue is not cspy related, it's just that if you include the elementarity resource, the definition of dominance doesn't help at all. 
For example, say resources are `[elementarity_Source, elementarity_1, elementarity_2]`.
Two different paths `[Source, 1]` and `[Source, 2]` will have resources:
`[1,1,0]` and `[1,0,1]`. 
When these two are compared for dominance, `[Source, 1]` doesn't dominate `[Source, 2]` because `[1,1,0]` is not < `[1,0,1]`, no matter what the total cost of the path is or the rest of the resources.
The same goes for the other way around.
This leads to the algorithm carrying every single possible label without being able to eliminate any.

**Comment by torressa** [comment]
Anyway, I think we can close this for now.
