### ISSUE TITLE
fixed number of vehicles

### ISSUE THREAD

**Issue by piaulous** [Kuifje02/vrpy#93]
Having an option to force the number of vehicles is something I would be interested in.
This could be done by extending the `num_vehicles` command with something like `use_all`, or setting up `min` / `max` values for the number of vehicles.

**Comment by Kuifje02** [comment]
The feature has been added. The argument is called `use_all_vehicles` (example in the docs [here](https://vrpy.readthedocs.io/en/dev/vrp_variants.html#limited-fleet)). Will make new relase by tomorow.

**Comment by piaulous** [comment]
Thank your very much!

**Comment by piaulous** [comment]
in some cases I now get an 'empty' route: ['Source', 'Sink']

**Comment by Kuifje02** [comment]
Aha, this is interesting...re opening.

**Comment by Kuifje02** [comment]
Ortools users have ran into this problem already : https://github.com/google/or-tools/issues/1351 : 

> This is generally a bad idea to add min values to cumul vars (e.g., number of used vehicles).
> You can easily run into infeasible problems. It would be better to constraint the max number of visits per vehicle.
> 
> If you want to model fairness, it should be reflected in the objective, not in hard constraints.

So @lperron basically suggests two options:

1. Constrain the number of stops per routes in order to force the required number of vehicles. It can be tricky to find this value (the good number of stops).
2. Use "fairness": minimize the maximum difference of duration between two routes. You can do this with the `minimize_global_span` argument: https://github.com/Kuifje02/vrpy/blob/96cc5501d05c341cc50f4377d15f27fbf422584a/vrpy/vrp.py#L74
But this changes the formulation and may leed to slower convergence.

**Comment by Kuifje02** [comment]
We can hard code the `use_all` option to enforce at least one visit with a warning that it is probably a bad approach and may lead to infeasible configurations.

**Comment by Kuifje02** [comment]
@piaulous routes `["Source","Sink"]` how have a very high cost and should not be part of the solution. I am closing the issue for now. Feel free to re open it if the next release is not satisfactory.
